spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
    devtools:
      restart:
        enabled: true
  freemarker:
    cache: false
    charset: UTF-8
    template-loader-path: classpath:/templates/
    suffix: .ftl
  datasource:
    url: jdbc:mysql://localhost:3306/music?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
  jpa:
    generate-ddl: true
server:
  servlet:
    session:
      timeout: 1800
